# Generated by Django 5.1.1 on 2024-11-23 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentModel',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('finance_name', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('mobile_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('address', models.TextField()),
                ('agent_type', models.CharField(max_length=20)),
                ('admin_id', models.CharField(max_length=10)),
                ('created_on', models.DateTimeField()),
                ('modified_on', models.DateTimeField()),
            ],
        ),
    ]
