# Generated by Django 5.1.1 on 2024-11-23 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('created_on', models.DateTimeField()),
                ('modified_on', models.DateTimeField()),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
