# Generated by Django 5.1.1 on 2024-12-29 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customermodel',
            old_name='agent_id',
            new_name='user_id',
        ),
    ]
