# Generated by Django 5.1.1 on 2024-12-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_rename_agent_id_customermodel_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='aadhar_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
