# Generated by Django 5.1.4 on 2025-01-25 05:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customermodel_aadhar_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='customer_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
