# Generated by Django 5.1.4 on 2025-01-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customermodel_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
