# Generated by Django 5.1.1 on 2024-11-23 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanModel',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('roi', models.DecimalField(decimal_places=2, max_digits=5)),
                ('emi_amount', models.IntegerField()),
                ('repayment_frequency', models.CharField(max_length=20)),
                ('number_of_installments', models.IntegerField()),
                ('lending_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customermodel')),
            ],
        ),
    ]
