# Generated by Django 5.1.1 on 2024-09-22 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanmodel',
            name='payments_done',
        ),
    ]
