# Generated by Django 5.1.1 on 2024-12-28 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanmodel',
            old_name='emi_amount',
            new_name='repayment_amount',
        ),
        migrations.RemoveField(
            model_name='loanmodel',
            name='roi',
        ),
    ]
