# Generated by Django 5.1.4 on 2025-01-19 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_rename_emi_amount_loanmodel_repayment_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanmodel',
            old_name='customer',
            new_name='customer_id',
        ),
    ]
