# Generated by Django 5.1.4 on 2025-01-26 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_rename_customer_loanmodel_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanmodel',
            name='lending_date',
            field=models.DateField(),
        ),
    ]
