# Generated by Django 5.1.1 on 2024-09-22 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('loans', '0002_remove_loanmodel_payments_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepaymentModel',
            fields=[
                ('repayment_id', models.AutoField(primary_key=True, serialize=False)),
                ('repayment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('comments', models.TextField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customermodel')),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loans.loanmodel')),
            ],
        ),
    ]
